### ISSUE TITLE
Enable/Configure shadcn for blog styling

### ISSUE THREAD

**Issue by TD-Syndicure** [akay4ty7/blog#5]

**Comment by akay4ty7** [comment]
@TD-Syndicure I am Stuck when it comes to applying CSS theme of my work. I run the steps to install and it asks me all the of the defaults etc. After I do this I am not sure how to make my project look similar to that of the shadcn-ui website. For now I wish to go with that theme but I am unsure how to do this. 

Another thing I noticed is that when I try to use shadcn-ui components I get the following for example:



![Image](https://github.com/user-attachments/assets/8317b2c0-29a1-4fcb-8f7d-07891734dd31)

I tried to see if the module shadcn-ui was there in my node_modules, but it is not. I am not sure how to use this correctly. 

Do you know what I can do here or if you have a resource to help me that would be great. I did try to use the docs but I was lost.

**Comment by TD-Syndicure** [comment]
Ok so this is where I may not have explained myself clearly when we were talking on the call the other night.

Shadcn is not a package that contains all the items you need but a set of prebuilt components that you add to your project individually and can style/edit/change how you want after you add them.

Example of the installed component:

![Image](https://github.com/user-attachments/assets/0d0b5f6a-0869-4286-858d-222c08cab75b)

Example of the component in use:

![Image](https://github.com/user-attachments/assets/73b57d5a-7930-4fc9-a847-b2f46c9664f0)
![Image](https://github.com/user-attachments/assets/32a9b580-7452-4aea-8431-ffbca4248e33)

So to use the card and install the card you need to follow the steps to install here:
https://ui.shadcn.com/docs/components/card you can click the copy icon to get the command to install it.



![Image](https://github.com/user-attachments/assets/d168a959-d6b5-4da3-8a06-662da4a1987b)



![Image](https://github.com/user-attachments/assets/87fc70a6-059a-4888-a450-34fc404e0dc3)



Copy paste this into your terminal:
npx shadcn-ui@latest add card

Then it will create the re-usable component in your components ui folder. Then you can import into your project using:
```typescript
import {
    Card,
    CardContent,
    CardFooter,
    CardHeader,
} from "@/components/ui/card";
```

And use it how you want:
```typescript
 <Card className="">
            <CardHeader>
            </CardHeader>
            <CardContent className="">

            </CardContent>
            <CardFooter className="">

            </CardFooter>
        </Card>
```
